### ISSUE TITLE
Iter8-trend integration w/ Kiali

### ISSUE THREAD

**Issue by huang195** [iter8-tools/iter8-trend#67]

**Comment by huang195** [comment]
@jadeyliu939 we can use this issue to document whatever design we come up with from our discussion.

**Comment by jadeyliu939** [comment]
Issues created in Kiali for supporting iter8-trend in Kiali 

1. [allow series-based x-axis](https://github.com/kiali/kiali/issues/2993)
2. [show timeless series charts ordered by time](https://github.com/kiali/kiali/issues/3022)
3. [Default labels grouping](https://github.com/kiali/kiali/issues/3023 )

**Comment by huang195** [comment]
Moving this issue to milestone #9

**Comment by jadeyliu939** [comment]
Comment from the Kiali on the 3 remaining feature requests.

=== From Joel and Lucas

Does it mean that these different metrics are stored as different labels with the same metric name? If so, then that's perhaps a problem. I guess you have your reasons to have designed metrics that way, but in Kiali it's expected to have consistent data (same unit, same scale..) within a metric.

E.g. there would be a CPU metric like "iter8_trend_cpu" and a memory metric like "iter8_trend_memory", but you are saying you have something like "iter8_trend{metric="cpu"}" and "iter8_trend{metric="memory"}" ? Is it possible for you to do the other way around? Then you could setup 1 chart per metric in Kiali dashboard, each chart having its own unit & y-axis.

====

**Comment by jadeyliu939** [comment]
SingleSelection option is now available for CustomMetric.

Please try - [http://169.47.192.206:32614/kiali/](http://169.47.192.206:32614/kiali/}  (admin/admin)

Application -> Reviews -> Iter8 Trend Metrics

**Comment by huang195** [comment]
@jadeyliu939 These look very good. I played around with Kiali using the above link, and I agree that getting rid of pod aggregation will be less confusing. One question is when Metrics is not selected, it's showing labels such as "v1", "v2", etc. From the y-axis, this looks like memory usage data. However, when Metrics is selected, it becomes "cpu,v1", "cpu,v2", etc. Is it possible to make labels consistent?

**Comment by huang195** [comment]
One other suggestion: the labels in the legend have a lot of repetitions, e.g., "networkbyteread,v1", "networkbyteread,v2", etc. Is it possible to put metric name as the y-axis label, and then change the labels in the legend to be "v1", "v2", etc. to make it a bit cleaner?

**Comment by huang195** [comment]
@jadeyliu939 Looking at your checklist above, do you think we have everything for integrating iter8-trend w/ kiali for v0.2 release? If so, do you want to close this issue? Also, did we say if we want to push anything to Kiali for this work or something we keep in iter8-tools repo for now? If something needs to be pushed upstream, maybe a separate issue to track that would be warranted.

**Comment by huang195** [comment]
Per discussion on scrum, @jadeyliu939 please open a new issue for v1.0 work. This issue is mostly for v0.2
